$(".newHire").click(function(){
	$("#comingGoing").val("New");
	$(".moreForm").html("<div class='form-group'><label for='phoneNumber'>Phone Number</label><input type='tel' class='form-control' name='phoneNumber' id='phoneNumber' placeholder='phoneNumber'></div><p><b>Office</b></p><div class='form-group radio'><label class='radio-inline'><input type='radio' name='office' id='officeOption1' value='Bridgeport'>Bridgeport</label><label class='radio-inline'><input type='radio' name='office' id='officeOption2' value='Hartford'>Hartford</label><label class='radio-inline'><input type='radio' name='office' id='officeOption3' value='New Haven'>New Haven</label></div><p><b>Position</b></p><div class='form-group radio' id='positionSel'><label class='radio-inline'><input type='radio' name='position' id='posCaseAdmin' value='Case Administrator'>Case Administrator</label><label class='radio-inline'><input type='radio' name='position' id='posCourtReporter' value='Court Reporter'>Court Reporter</label><label class='radio-inline'><input type='radio' name='position' id='posDocketClerk' value='Docket Clerk'>Docket Clerk</label><label class='radio-inline'><input type='radio' name='position' id='posFinance' value='Finance'>Finance</label><label class='radio-inline'><input type='radio' name='position' id='posJudge' value='Judge'>Judge</label><label class='radio-inline'><input type='radio' name='position' id='posLawClerk' value='Law Clerk'>Law Clerk</label></div><button type='submit' class='btn btn-default'>Submit</button>");
});

$(".separatingEmp").click(function(){
	$("#comingGoing").val("Separating");
	$(".moreForm").html("<p><b>Office</b></p><div class='form-group radio'><label class='radio-inline'><input type='radio' name='office' id='officeOption1' value='Bridgeport'>Bridgeport</label><label class='radio-inline'><input type='radio' name='office' id='officeOption2' value='Hartford'>Hartford</label><label class='radio-inline'><input type='radio' name='office' id='officeOption3' value='New Haven'>New Haven</label></div><p><b>Position</b></p><div class='form-group radio' id='positionSel'><label class='radio-inline'><input type='radio' name='position' id='posCaseAdmin' value='Case Administrator'>Case Administrator</label><label class='radio-inline'><input type='radio' name='position' id='posCourtReporter' value='Court Reporter'>Court Reporter</label><label class='radio-inline'><input type='radio' name='position' id='posDocketClerk' value='Docket Clerk'>Docket Clerk</label><label class='radio-inline'><input type='radio' name='position' id='posFinance' value='Finance'>Finance</label><label class='radio-inline'><input type='radio' name='position' id='posJudge' value='Judge'>Judge</label><label class='radio-inline'><input type='radio' name='position' id='posLawClerk' value='Law Clerk'>Law Clerk</label></div><button type='submit' class='btn btn-default'>Submit</button>");
});

function confirmForm(form) {
	return confirm('If the information entered is correct, please hit OK.');
}
